### ISSUE TITLE
Machine parseable output

### ISSUE THREAD

**Issue by CendioOssman** [netromdk/vermin#48]
**Is your feature request related to a problem? Please describe.**
We are using vermin from our CI and want to provide as much feedback as possible when something fails. So we'd like to be able to get the results from vermin and feed back in to the reports given.

**Describe the solution you'd like**
All result data in a format that can easily be parsed by another piece of software:

 * Aggregated minimum versions
 * List of detected requirements with file, line, column, versions and reason

E.g.:

```
foo.py:17:5:2.6:3.0:__future__.print_function
```

**Describe alternatives you've considered**
Parsing the current output. It is likely to break in the future though as it can easily change given that it's for humans, and not other software.

**Comment by gousaiyang** [comment]
+1. I would also like to see a stable parseable report (similar to [`git status --porcelain`](https://git-scm.com/docs/git-status#Documentation/git-status.txt---porcelainltversiongt)). I was thinking about having or making a VSCode extension for vermin so that code compatibility problems could be detected even earlier (during coding, before CI).

**Comment by netromdk** [comment]
It's a good idea with a format that's easier to parse. The output could also be JSON so that it doesn't matter with special separators and such?

**Comment by CendioOssman** [comment]
That probably works for us, but JSON is not really useful from shell scripts. So it would narrow the audience a bit.

**Comment by netromdk** [comment]
With the format you proposed, I guess it could just end with a final line that describes the aggregated two minimum versions results. Maybe with a blank line before the final, aggregated result, like:
```
foo.py:17:5:2.6:3.0:__future__.print_function
bar.py:10:_:2.3:3.0:some_module
baz.py:234:2:2.7:3.4:special_module.function(some_kwarg)

2.7:3.4
```

And if a column isn't known it could put `_`.

**Comment by CendioOssman** [comment]
I think comments are best left out of such data. This will likely not be seen by a human after all. Someone can just re-run the command without `--porcelain` if they want extra information.

**Comment by netromdk** [comment]
Yes, that is a good point.

**Comment by gousaiyang** [comment]
```
Traceback (most recent call last):
  File "/path/vermin.py", line 2, in <module>
    from vermin.main import main
  File "/path/vermin/__init__.py", line 1, in <module>
    from .main import main
  File "/path/vermin/main.py", line 4, in <module>
    from .config import Config
  File "/path/vermin/config.py", line 3, in <module>
    from .formats import Formats
ModuleNotFoundError: No module named 'vermin.formats'
```

Looks like you forgot to check in `formats.py`.

**Comment by netromdk** [comment]
Ah.. Hehe. Added it now.

**Comment by gousaiyang** [comment]
I feel it better not to show "Ignoring member ... because it's user-defined!". I guess these messages are only used for debugging (identifying false negatives), which are not so helpful as part of the default machine parsable output. If someone wants to see this they can use `-vvvv`.

Also I see some extra newlines inside the output when running `./vermin.py -f parsable .` (against the vermin codebase itself).

**Comment by netromdk** [comment]
Good point. I've pushed a fix for the extra newlines and removed the level 4 verbosity messages by effectively setting parsable on verbosity level 3 since that's when the line and column numbers start.

**Comment by netromdk** [comment]
@CendioOssman Do you have any feedback? Otherwise, I will merge it tomorrow or Monday. :-)

**Comment by CendioOssman** [comment]
Sorry, things are a bit busy here. I'll see if I can do a test today.

**Comment by netromdk** [comment]
That's alright. This is one of the last things before a new 1.0.0 release, I think.

**Comment by CendioOssman** [comment]
So I've done some testing now, and on first look it looks very nice. I'm seeing this error output though:

```
/opt/thinlinc/modules/aes.py:643:25: error: invalid syntax: raise ValueError, emsg % keysize
```

In normal mode with `-v` it shows:
```
~2, ~3       /opt/thinlinc/modules/aes.py
```

A summary for every file would be nice as well. It avoid having to duplicate the version logic, and it allows me to verify that every file has been analysed by vermin. Perhaps the same format by no line number and no description?

And have you thought about if a file (or other field) contains a `:`? Some escaping or filtering might be needed in such a case.

**Comment by netromdk** [comment]
Thanks! Can you give me that file so I can try to reproduce it? Haven't seen that error before.

I can definitely make a summary per file. Good idea.

":" is not allowed in file paths on Windows but can happen on *nix actually. So I'll think about escaping perhaps. I don't use in messages. I have an assertion on the file path in the AST visitor which shouldn't be done if it escapes as `\:`. But that would be a little nonstandard though I think it's still an okay solution for weird file paths.

**Comment by CendioOssman** [comment]
Sure, you can find a copy here:

https://github.com/aleaxit/slowaes/blob/master/python/aes.py

**Comment by netromdk** [comment]
You get the error because the syntax is Python 2 only, it's not valid Python 3:
```py
emsg = 'Invalid keysize, %s. Should be one of (16, 24, 32).'
raise ValueError, emsg % keysize // <--
```

If you use verbose 2+ you'll see it also with normal mode:
```
% ./vermin.py -vv examples/aes.py
Detecting python files..
Analyzing using 8 processes..
/Users/netrom/git/vermin/examples/aes.py:643:25: error: invalid syntax: raise ValueError, emsg % keysize
~2, ~3       /Users/netrom/git/vermin/examples/aes.py
Minimum required versions: ~2, ~3
```

**Comment by gousaiyang** [comment]
As for weird filenames, actually I've already tried that last time. When filename contains `:` or the newline character, parsing the output may run into trouble. However I've also tried this with `flake8` and found that `flake8` is not considering this problem at all. And generally string parsing in the shell ecosystem suffers from some corner cases that may break integrity of strings or make parsing harder, so may be we just let it be (filenames containing newlines should be very rare in reality, and filenames containing `:` is discouraged if developing a cross platform project since it's not valid on Windows).

**Comment by netromdk** [comment]
Pushed a new round of fixes.

@CendioOssman  Is this what you meant with the summary for each file?

I also agree with @gousaiyang and I don't find it to be a big problem, but I still made a very simple, nonstandard escaping using `\:`.

```
/Users/netrom/git/vermin/examples/abc.py:1:7:2.6:3.0:'abc' module
/Users/netrom/git/vermin/examples/abc.py:2::!2:3.4:'abc.ABC' member
/Users/netrom/git/vermin/examples/abc.py:::!2:3.4

/Users/netrom/git/vermin/examples/annotations.py:2::!2:3.0:annotations
/Users/netrom/git/vermin/examples/annotations.py:6::!2:3.6:variable annotations
/Users/netrom/git/vermin/examples/annotations.py:::!2:3.6

/Users/netrom/git/vermin/examples/special\:file.py:1:7:!2:3.9:'zoneinfo' module
/Users/netrom/git/vermin/examples/special\:file.py:::!2:3.9

!2
3.9
```

**Comment by CendioOssman** [comment]
> You get the error because the syntax is Python 2 only, it's not valid Python 3:

Indeed. But shouldn't it give me `2.something !3` in that case?

> @CendioOssman is this what you meant with the summary for each file?

Yes, this looks nice. I would suggest a trailing `:` though to keep the number of fields constant.

There's also an empty line between each file now. Was that intentional?

> I also agree with @gousaiyang and I don't find it to be a big problem, but I still made a very simple, nonstandard escaping using `\:`.

The problem is escaping needs to be fully thought out though, so now you need to consider if there is a `\` in the file name.

I agree that `:` is rare. But I don't like silent breakage. So I would be fine with a simple assert or error or something for those files for now.

**Comment by CendioOssman** [comment]
> I would suggest a trailing `:` though to keep the number of fields constant

Same thing for the final verdict. So:

```
:::2.4:3.2:
```

rather than
```
2.4
3.2
```

**Comment by netromdk** [comment]
> > You get the error because the syntax is Python 2 only, it's not valid Python 3:

> Indeed. But shouldn't it give me `2.something !3` in that case?

I can only mark with a minimum version if I can match an error message and _know_ that it is true. In this case, syntax error is simply too vague to react to it.

> > @CendioOssman is this what you meant with the summary for each file?

> Yes, this looks nice. I would suggest a trailing `:` though to keep the number of fields constant.

Good point. Will add.

> There's also an empty line between each file now. Was that intentional?

It was, but I see that it might not be relevant anyway. Will remove.

> > I also agree with @gousaiyang and I don't find it to be a big problem, but I still made a very simple, nonstandard escaping using `\:`. 

> The problem is escaping needs to be fully thought out though, so now you need to consider if there is a `\` in the file name.
> I agree that `:` is rare. But I don't like silent breakage. So I would be fine with a simple assert or error or something for 
> those files for now.

Hmm yes. Well, I kind of prefer my old solution with the assertion anyway so might put that back in. Then it won't be silent either.

Thanks for the feedback. I'll make the changes tonight. Including the better visualization of the final verdict line, too. 👍🏻 And then with no empty lines anywhere.

**Comment by netromdk** [comment]
> Indeed. But shouldn't it give me 2.something !3 in that case?

Come to think about it.. If you get a syntax error in Python 2.x then in that moment that file certainly isn't compatible with Python 2. And same for Python 3.x. In your case, it's not compatible with Python 3.x so it should show `2.x, !3` (with the specific 2.x for that situation). I'll look into that. Thanks.

**Comment by gousaiyang** [comment]
I guess this behavior of reporting `~2, ~3` upon syntax error is probably due to file detection heuristics (e.g. finding text files containing Python code but without `.py` extensions) and fault tolerance? If a file has (fatal) syntax errors (not related to Python 2/3 or other version compatibility issues), the current logic conservatively reports `~2, ~3`.

However I think it's better to tell users that some of their files have syntax errors if the file already has a `.py` extension (or is explicitly given in the command line file list). Then how do we differentiate "fatal syntax errors" and "Python 2 only syntax" and "Python 3.9 only syntax but vermin is running in Python < 3.9"? `vermin` makes use of the builtin `ast` module, and in 3.8 `ast.parse` supports a `feature_version` parameter to parse code **as** a given version, but currently it only supports parsing code as major version 3.

**Comment by netromdk** [comment]
Yes, that is correct. Right now for syntax errors, it will look for known scenarios like `"missing parentheses in call to 'print'"` which finds `print expr` statements not supported in py3, for instance, but otherwise it will just print the syntax error information and move on. This is also because I only want to report anything if it is a known thing - in general that isn't known at all for syntax errors that can occur arbitrarily. So I think this might need some more thorough thought before doing anything differently.

Maybe it could collect a list of file paths that had syntax errors in them and report that list in the end if `--no-tips` isn't specified.

**Comment by netromdk** [comment]
Alright, @CendioOssman, I pushed the fixes you requested such that the results are now:
```
/Users/netrom/git/vermin/examples/abc.py:1:7:2.6:3.0:'abc' module
/Users/netrom/git/vermin/examples/abc.py:2::!2:3.4:'abc.ABC' member
/Users/netrom/git/vermin/examples/abc.py:::!2:3.4:
/Users/netrom/git/vermin/examples/annotations.py:2::!2:3.0:annotations
/Users/netrom/git/vermin/examples/annotations.py:6::!2:3.6:variable annotations
/Users/netrom/git/vermin/examples/annotations.py:::!2:3.6:
:::!2:3.6:
```

And the `:`-in-path assertion is back in the source visitor.

**Comment by gousaiyang** [comment]
> And the :-in-path assertion is back in the source visitor.

If we have assertions I thinks it's better to also assert for filenames containing `\n`. Also when a file whose name contains `:` contains syntax errors, currently it still shows up in the parsable report.

**Comment by netromdk** [comment]
I guess when the parsable format is used, the detection logic could just ignore all file paths containing ":"?

**Comment by netromdk** [comment]
If there are no objections to the parsable format as it is now, I'm planning to release Vermin v1.0.0 on Monday perhaps.

**Comment by gousaiyang** [comment]
One minor problem: when a file contains syntax errors

`/path/to/vermin/misc/travis/after_success.sh:4:7: error: invalid syntax: if [[ $TRAVIS_PYTHON_VERSION != 2.7 && $TRAVIS_PYTHON_VERSION != 3.4 ]]; then`

It is better to make this output like:

``/path/to/vermin/misc/travis/after_success.sh:4:7:~2:~3: error: invalid syntax: if [[ $TRAVIS_PYTHON_VERSION != 2.7 && $TRAVIS_PYTHON_VERSION != 3.4 ]]; then``

so that `error: invalid syntax` won't go into the fields of version numbers when parsed by `cut -d ':' -f ...`.

**Comment by netromdk** [comment]
Thanks, that's a good point. I've pushed that change.

**Comment by CendioOssman** [comment]
Seems to work fine now. It breaks on this though:

```python
print """Print
With line break"""
```

It tries to print the offending statement, which includes a line break and screw up the output:

```
$ ./vermin.py --format parsable ./foo.py
foo.py:2:33:2.0:!3:info: `print """Print
With line break"""` requires 2.0
foo.py:::2.0:!3:
:::2.0:!3:
```


(I also would prefer it to be pessimistic and stating `!3` on syntax errors, but that's not really related to this issue)

**Comment by netromdk** [comment]
Nice catch. I've pushed a fix that changes all newlines to be escaped like so:
```
/path/to/print.py:2:7:2.0:!3:info: `print """Print\nWith line break"""` requires 2.0
```
Only for things related to parsable format, though.

It could make sense to have a pessimistic mode. Whether it should be the default will need some thought but I do see the point of it: if there is a syntax error, then it's definitely true it won't work with the version of Python parsing it. But it is a little bit more complex than that, though. Let's take it up in another issue.

**Comment by CendioOssman** [comment]
Seems to work well now for our case. Thanks. :)

**Comment by netromdk** [comment]
It has been merged to `master`. Thanks again!

**Comment by netromdk** [comment]
@CendioOssman I implemented the `--pessimistic` argument which interprets syntax errors as the Python version in use being incompatible (in the `dev` branch currently).

**Comment by gousaiyang** [comment]
I just noticed one problem about the parsable format. Looks like all paths are converted to absolute paths before processing, thus on Windows, file paths will always contain exactly one `:` character in the drive part (if using local paths, not network paths), which makes `vermin` always report `No files specified to analyze!` on Windows when using `--format parsable`. Maybe we'll just allow `:` for Windows? A smart parser can try to parse the file path based on the fact that the second field (line number) could only be empty or a valid integer.

**Comment by netromdk** [comment]
@gousaiyang thanks. I thought I had caught all cases. In `SourceVisitor` I already allow `:` on Windows, but I've just pushed a fix to `master` that allows `:` on Windows for detection logic. Note that on Windows, it isn't allowed to have `:` except for the drive part anyway.

**Comment by gousaiyang** [comment]
> Note that on Windows, it isn't allowed to have : except for the drive part anyway.

A very rare corner case is [Alternate data streams](https://en.wikipedia.org/wiki/NTFS#Alternate_data_streams_(ADS)), but I think few people will use it in production. Also not sure if UNC Paths can contain `:`. But since we already ignore file paths containing `:` on Unix, we can also ignore them on Windows. The only important thing to care about is to make normal paths like `C:\Dir\file` work with vermin.

**Comment by netromdk** [comment]
Interesting. Didn't know about ADS, but yeah, it's fine as it is now. I've pushed a new test case (on `dev`) that checks files detected when running with parsable format enabled (I recently started also testing macOS and Windows in addition to on Linux).

**Comment by netromdk** [comment]
Interesting. Didn't know about ADS, but yeah, it's fine as it is now. I've pushed a new test case (on `dev`) that checks files detected when running with parsable format enabled (I recently started also testing macOS and Windows in addition to on Linux).
